<?php

return [
    '128162' => [
        'school_name' => 'Baybay Central School',
        'school_head' => 'BONITA, JOVY O.',
        'school_head_position' => 'School Principal-II',
        'assigned_admin' => 'Decipulo, Maita Shane P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128164' => [
        'school_name' => 'Ozamiz City Central School',
        'school_head' => 'BUCOG, EUGENIO C.',
        'school_head_position' => 'School Principal II',
        'assigned_admin' => 'Culminas, Lizcel C.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128165' => [
        'school_name' => 'Bacolod Elementary School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Pelaez, Kristine P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128166' => [
        'school_name' => 'Catadman Elementary School',
        'school_head' => 'MARITES B. BARRIENTOS',
        'school_head_position' => 'SCHOOL PRINCIPAL-II',
        'assigned_admin' => 'Yoldan, Abegail M.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128168' => [
        'school_name' => 'Doña Consuelo Elementary School',
        'school_head' => 'Paredes, Melanie T',
        'school_head_position' => 'Elementary School Principal-I',
        'assigned_admin' => 'Gomonit, Mary Grace P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128169' => [
        'school_name' => 'Embargo Elementary School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Decipulo, Maita Shane P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128170' => [
        'school_name' => 'Gango Elementary School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Sebarios, Nellie P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128171' => [
        'school_name' => 'Gotocan Elementary School',
        'school_head' => 'LLOYD RALPH R. CESNORIO',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'Dagaas, Claire Marie V.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128172' => [
        'school_name' => 'Labo Central School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Alamin, Marissa E.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128173' => [
        'school_name' => 'Antero D. Hinagdanan Elementary School',
        'school_head' => 'RUPINTA JUPEY Q.',
        'school_head_position' => 'Head Teacher III',
        'assigned_admin' => 'Aviso, Jonaly, A.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128174' => [
        'school_name' => 'Maningcol Central School',
        'school_head' => 'COLARTE, JUVES C.',
        'school_head_position' => 'Elementary School Principal I',
        'assigned_admin' => 'Paez, Lyn B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128175' => [
        'school_name' => 'San Antonio Elementary School',
        'school_head' => 'CABURAL, RAMIL G.',
        'school_head_position' => 'Elementary School Principal II',
        'assigned_admin' => 'Sayson, Adrian L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128177' => [
        'school_name' => 'Andrea D. Costonera Elementary School',
        'school_head' => 'Simblante, Clarinda Fe L.',
        'school_head_position' => 'Elementary School Principal II',
        'assigned_admin' => 'Almoite, Snooky L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128178' => [
        'school_name' => 'Maximino S. Laurete, Sr. Central School',
        'school_head' => 'Sagario, Marjorie A.',
        'school_head_position' => 'Elementary School Principal III',
        'assigned_admin' => 'Abcede, Lorena G.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128181' => [
        'school_name' => 'Felipe Carreon Central School',
        'school_head' => 'Lagus, Melanie G.',
        'school_head_position' => 'Elementary School Principal II',
        'assigned_admin' => 'Gerondio, Analyn P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128182' => [
        'school_name' => 'Guimad Elementary School',
        'school_head' => 'Genaline A. Lopez',
        'school_head_position' => 'Teacher III,TIC',
        'assigned_admin' => 'Fabriga, Robeth Wilbur M.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128186' => [
        'school_name' => 'Roman E. Mabanag, Sr. Elementary School',
        'school_head' => 'Bello, Lady Shammah E.',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'Lagoc, Genie Vah C.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128187' => [
        'school_name' => 'Antero U. Roa Central School',
        'school_head' => 'Pondar, Mary Jane A.',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'CANASTRA, DENNIS M.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128188' => [
        'school_name' => 'Pershing Tan Queto, Sr. Elementary School',
        'school_head' => 'OCANG, CHERRELYN M.',
        'school_head_position' => 'Teacher III, TIC',
        'assigned_admin' => 'Siso, John Rey B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128190' => [
        'school_name' => 'Balintawak Elementary School',
        'school_head' => 'Rusiana, Jocelyn G.',
        'school_head_position' => 'Teacher VII',
        'assigned_admin' => 'Moreno, Louie J.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128191' => [
        'school_name' => 'Bongbong Elementary School',
        'school_head' => 'Caseros, Joselito D.',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'Barbadillo, Anna Pearl B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128195' => [
        'school_name' => 'Gala Elementary School',
        'school_head' => 'Paderanga, Melchie A .',
        'school_head_position' => 'Head Teacher II',
        'assigned_admin' => 'NINI,SHEILA MARIE C.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128196' => [
        'school_name' => 'Gregorio A. Saquin Elementary School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Manuel, Ethel R.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128197' => [
        'school_name' => 'Juan A. Acapulco Elementary School',
        'school_head' => 'Rubio, Sesame C.',
        'school_head_position' => 'Principal 1',
        'assigned_admin' => 'Jumawid, Adelfa S.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128198' => [
        'school_name' => 'Labinay Elementary School',
        'school_head' => 'Amisola, Joseph M.',
        'school_head_position' => 'Principal 1',
        'assigned_admin' => 'Pangilinan, Yulane E.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128199' => [
        'school_name' => 'Diego Tuastomban Elementary School',
        'school_head' => 'Baco, Lida L.',
        'school_head_position' => 'Principal 1',
        'assigned_admin' => 'Baybado, Gladys L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128201' => [
        'school_name' => 'Pulot Elementary School',
        'school_head' => 'Ares, Jeffrey B.',
        'school_head_position' => 'ESHT-III',
        'assigned_admin' => 'Baguio, Charity O.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '128203' => [
        'school_name' => 'Narciso B. Ledesma Central School',
        'school_head' => 'Bandiala, Angel Grace E.',
        'school_head_position' => 'Principal 1',
        'assigned_admin' => 'Fiel, Glaiza D.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203501' => [
        'school_name' => 'Hilarion J. Ramiro Jr. Elementary School',
        'school_head' => 'Leo C. Acebedo',
        'school_head_position' => 'ESHT III',
        'assigned_admin' => 'Montefalcon, Zenelyn J.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203502' => [
        'school_name' => 'Mintalar Elementary School',
        'school_head' => 'Emelito C. Viernes',
        'school_head_position' => 'ESHT III',
        'assigned_admin' => 'Dagaas, Claire Marie V.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203504' => [
        'school_name' => 'Dalapang Elementary School',
        'school_head' => 'Garnada, Adonis D.',
        'school_head_position' => 'ESHT-III',
        'assigned_admin' => 'Saguin, Cherely E.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203505' => [
        'school_name' => 'Tipan Elementary School',
        'school_head' => 'Marlon A. Gordove',
        'school_head_position' => 'Elementary School Principal I',
        'assigned_admin' => 'Castro, John Rey F.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203506' => [
        'school_name' => 'Capucao C Elementary School',
        'school_head' => 'Peñaranda, Lou E.',
        'school_head_position' => 'Master Teacher II',
        'assigned_admin' => 'Velayo, Ma. Fe Rizenbil P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '203507' => [
        'school_name' => 'Sta. Cruz Elementary School',
        'school_head' => 'Duma-og, Cheryl V.',
        'school_head_position' => 'Principal 1',
        'assigned_admin' => 'Guangco, Jene S.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304161' => [
        'school_name' => 'Labinay National High School',
        'school_head' => 'Acal, Emma A.',
        'school_head_position' => 'Head Teacher III',
        'assigned_admin' => 'Hermosisima, Joar G.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304162' => [
        'school_name' => 'Tabid National High School',
        'school_head' => 'VIERNES, ESTER F.',
        'school_head_position' => 'Secondary School Principal I',
        'assigned_admin' => 'Cabrisos, Michelle Ann T.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304163' => [
        'school_name' => 'Labo National High School',
        'school_head' => 'Pongase, Edilberto, Jr. B.',
        'school_head_position' => 'Secondary School Principal II',
        'assigned_admin' => 'Betonio, Kuenie',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304164' => [
        'school_name' => 'Jose Lim Ho National High School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Navarez, Claudia Faith B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304165' => [
        'school_name' => 'San Antonio National High School',
        'school_head' => 'Pines, Johnaline D.',
        'school_head_position' => 'Head Teacher I',
        'assigned_admin' => 'Sebarios, Nellie P.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304166' => [
        'school_name' => 'Montol National High School',
        'school_head' => 'BONGCAWIL, ALIE A.',
        'school_head_position' => 'Assistant School Principal- II',
        'assigned_admin' => 'Yoldan, Alberto Jr. L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '304167' => [
        'school_name' => 'Ozamiz City National High School',
        'school_head' => 'ABAMONGA, LILIBETH Y.',
        'school_head_position' => 'Secondary School Principal III',
        'assigned_admin' => 'Lagoc,  Genie Vah C.',
        'assigned_admin_position' => 'Administrative Officer II-OIC AOIV',
    ],
    '304168' => [
        'school_name' => 'Ozamiz City School of Arts and Trades',
        'school_head' => 'ALINDO, JEAN B.',
        'school_head_position' => 'Secondary School Principal III',
        'assigned_admin' => 'Acierto, Brenda O.',
        'assigned_admin_position' => 'Adminstrative Officer IV',
    ],
    '304169' => [
        'school_name' => 'Pulot National High School',
        'school_head' => 'Junriel B. Sinarillos',
        'school_head_position' => 'Secondary School principal I',
        'assigned_admin' => 'Macalisang, Mirose C.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '304170' => [
        'school_name' => 'Gala National High School',
        'school_head' => 'Pescador, Darlene Sheila J.',
        'school_head_position' => 'Head Teacher III',
        'assigned_admin' => 'Pabriga, Bebe Jay P.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '500699' => [
        'school_name' => 'Cogon Integrated School',
        'school_head' => 'Ponce,Lalaine Y.',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'Gacasan, Nine Mar A.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '500700' => [
        'school_name' => 'Malaubang Integrated School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Ylanan, April Rose R.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '500701' => [
        'school_name' => 'Misamis Annex Integrated School',
        'school_head' => 'Candelaria P. Maghanoy',
        'school_head_position' => 'Head Teacher II',
        'assigned_admin' => 'Guangco, Maria Elena L.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '501205' => [
        'school_name' => 'Cruz Lanzado Saligan Integrated School',
        'school_head' => '',
        'school_head_position' => '',
        'assigned_admin' => 'Laroya, Joffy Sandrey O.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '501206' => [
        'school_name' => 'Jacinto Nemeno Integrated School',
        'school_head' => 'Jorenda P. Solitario',
        'school_head_position' => 'Principal  I',
        'assigned_admin' => 'Pelitones, Cherley S.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '501209' => [
        'school_name' => 'Marcelino C. Regis Integrated School',
        'school_head' => 'Sialana, Rolito M.',
        'school_head_position' => 'Principal I',
        'assigned_admin' => 'Ada, Gerfe M.',
        'assigned_admin_position' => 'Adminstrative Officer II',
    ],
    '502051' => [
        'school_name' => 'Sancho Capa Integrated School',
        'school_head' => 'Buenasir J. Abapo',
        'school_head_position' => 'Principal II',
        'assigned_admin' => 'Pagador, Teresita L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502052' => [
        'school_name' => 'Sangay Integrated School',
        'school_head' => 'Credo,Jane A.',
        'school_head_position' => 'Elementary School Principal 1',
        'assigned_admin' => 'Luna, Susith L.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502053' => [
        'school_name' => 'Sinusa Integrated School',
        'school_head' => 'Ludivico B. Barrientos',
        'school_head_position' => 'Principal II',
        'assigned_admin' => 'Smith, Mary Grace B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502054' => [
        'school_name' => 'Capucao Integrated School',
        'school_head' => 'TAYONG, POLEY M.',
        'school_head_position' => 'Head Teacher I',
        'assigned_admin' => 'Libor, Jeffrey S.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502410' => [
        'school_name' => 'Dimaluna Integrated School',
        'school_head' => 'Garnada, Maida S.',
        'school_head_position' => 'Elem. Sch. Principal I',
        'assigned_admin' => 'Ramayrat, Dinalyn A.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502411' => [
        'school_name' => 'Domingo A. Barloa Integrated School',
        'school_head' => 'Gaabucayan, Miraluna M.',
        'school_head_position' => 'Elementary School Principal II',
        'assigned_admin' => 'Ostia, Jelyn B.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502412' => [
        'school_name' => 'Faustino C. Decena Integrated School',
        'school_head' => 'Salvador, Lydia G',
        'school_head_position' => 'Elementary School Principal 1',
        'assigned_admin' => 'Galay, Sharon Z.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
    '502413' => [
        'school_name' => 'Guingona Integrated School',
        'school_head' => 'ACAPULCO, GEM P.',
        'school_head_position' => 'Head Teacher- II',
        'assigned_admin' => 'Candawan, Jet A.',
        'assigned_admin_position' => 'Administrative Officer II',
    ],
];
